export enum ApiCallPaths {
  apiUrl = "https://localhost:44301/",
  registerPath = "api/Accounts/Register/",
  loginPath = "api/Accounts/Login/",
  getUserById = "api/Accounts/GetUserById/",
  getCurrentUserPath = "api/Accounts/GetCurrentUser/",

  createSessionPath = "api/Session/CreateSession/",
  activeFormPath = "api/Session/ActiveForm/",
  activeSessionPath = "api/Session/ActiveSession/",
  getAllSessionsPath = "api/Session/RecruitmentSessions/",
  updateSessionPath = "api/Session/UpdateSessionInfo/",
  getFormFromSession = "api/Session/SessionForm/",
  getSessionById = "api/Session/",
  deleteSession = "api/Session/DeleteSession/",
  UpdateFormInfo = "api/Session/UpdateForm/",

  postWorkshop = "api/Session/PostWorkshop",
  getWorkshopsBySessionId = "api/Session/Workshops/",
  getWorkshopById = "api/Session/Workshop/",
  deleteWorkshop = "api/Session/Workshop/Delete/",
  getUsersEligibleForSchedule = "api/Session/Workshop/ParticipantsToBeScheduled/",
  postWorkshopSchedule = "api/Session/Workshop/Schedule",

  addFormAnswrs = "api/Participants/AddFormResponse/",
  getSessionParticipants = "api/Participants/GetSessionsParticipants/",
  getParticipantAnswer = "api/Participants/FindParticipantAnswer/",
  getPaticipantStatus = "api/Participants/FindParticipantStatus/",
  postFormFeedback = "api/Participants/PostFormFeedback",
}
